stages:
  - build
  - test
  - deploy

test:
  stage: test
  script:
    - docker-compose -f docker-compose.test.yaml up --build --abort-on-container-exit
    - docker-compose -f docker-compose.test.yaml logs test-api
  after_script:
    - docker-compose -f docker-compose.test.yaml down -v
  only:
    - main

build:
  stage: build
  script:
    - docker-compose -f docker-compose.prod.yaml build
  only:
    - main

deploy:
  stage: deploy
  script:
    - cp $ENV ./.env
    - docker-compose -f docker-compose.prod.yaml down
    - docker-compose -f docker-compose.prod.yaml up -d
  only:
    - main

