stages:
  - update
  - build
  - test
  - deploy

update:
  stage: update
  script:
    - mkdir -p /builds/pavelklet-group/web_chat
    - cd /builds/pavelklet-group/web_chat
    - |
      if [ ! -d .git ]; then
        git clone $CI_REPOSITORY_URL .
      fi
    - git reset --hard HEAD
    - git clean -fd
    - git pull origin $CI_COMMIT_REF_NAME
  only:
    - main
    -
test:
  stage: test
  script:
    - docker-compose -f docker-compose.test.yaml up --build --abort-on-container-exit
    - docker-compose -f docker-compose.test.yaml logs test-api
  after_script:
    - docker-compose -f docker-compose.test.yaml down -v
  only:
    - main

build:
  stage: build
  script:
    - cp $ENV ./.env
    - docker-compose -f docker-compose.prod.yaml build
  only:
    - main

deploy:
  stage: deploy
  script:
    - cp $ENV ./.env
    - docker-compose -f docker-compose.prod.yaml up -d
  only:
    - main

