stages:
  - build
  - test
  - deploy

test:
  stage: test
  script:
    - docker-compose -f docker-compose.test.yaml up --build --abort-on-container-exit
    - docker-compose -f docker-compose.test.yaml logs test-api
  after_script:
    - docker-compose -f docker-compose.test.yaml down -v

build:
  stage: build
  script:
    - cp $ENV ./.env
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker-compose -f docker-compose.yaml build
    - docker-compose -f docker-compose.yaml push
  only:
    - main

deploy:
  stage: deploy
  script:
    - docker-compose pull
    - docker-compose up -d
  only:
    - main

