
services:
  test-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: "no"
    env_file:
      - .env.test
    command: >
      bash -c "
      poetry run pytest -s -v"
    depends_on:
      - test_db
    networks:
      - test-net
  test_db:
    image: postgres:16
    restart: always
    env_file: .env.test
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST_AUTH_METHOD: trust
    tmpfs:
      - /var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - test-net

networks:
  test-net:
    driver: bridge